name: rapid-cds-parser

on: [ push, pull_request ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    
  test:
    name: Test
    
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Unit
      run: cargo test --verbose
      
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: "Install external dependencies"
      run: |
        rustup component add rustfmt
        rustfmt --version
    - name: Lint
      run: rustfmt ./src/main.rs --check

  code-scan:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: reports
